### ISSUE TITLE
Suggestion: minify gopherjs code

### ISSUE THREAD

**Issue by jackkleeman** [sagiegurari/node-go-require#3]
I think the gopherjs build command should have an -m command to produce minified code; the gopherjs tool is better at minifying its out than any other minifier, so this is preferable to minifying the resulting code manually.

**Comment by sagiegurari** [comment]
Thanks for the suggestion, I'll think about how to set it up so the require would do minify if you wish to (probably by setting some env var).

**Comment by sagiegurari** [comment]
In order to generate minified javascript code, first set the following environment variable:

```sh
NODE_GO_REQUIRE_MINIFY=TRUE
```
